In [1]:
import numpy as np

In [2]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [3]:
# can store as numpy structured arrays to associate info better

x = np.zeros(4, dtype=int)

In [4]:
data = np.zeros(4, dtype={'names': ('name', 'age', 'weight'), 'formats': ('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [7]:
# U10 ==> unicode max length of 10
# i4  ==> 4 byte int (32 bit)
# f8  ==> 8 byte float (64 bit)

In [8]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [9]:
# get all names
print(data['name'])

['Alice' 'Bob' 'Cathy' 'Doug']


In [10]:
# get first row of data
print(data[0])

('Alice', 25, 55.)


In [11]:
# get names where age is under 30

data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [12]:
# can also declare with a compound type

np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [13]:
## More advanced compound types

In [14]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
## Record Arrays

In [16]:
data['age']

array([25, 45, 37, 19], dtype=int32)

In [18]:
# record arrays make accessing a bit easier, but slower

data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19], dtype=int32)

In [19]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

83.5 ns ± 0.72 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
2.56 µs ± 13.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.35 µs ± 60.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
